"""empty message

Revision ID: 606198189143
Revises: a4076ea888cc
Create Date: 2020-06-17 15:09:58.100643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '606198189143'
down_revision = 'a4076ea888cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_users', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_users', sa.Column('level', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
