"""empty message

Revision ID: a4076ea888cc
Revises: 87fa3ea401ad
Create Date: 2020-06-17 15:09:01.566127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4076ea888cc'
down_revision = '87fa3ea401ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_users', sa.Column('level', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_users', 'level')
    # ### end Alembic commands ###
